server:
    port: 8080
#    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG
#security:
#  user:
#    name: admin
#    password: admin123
#  basic:
#    realm: Please provide your authentication details
spring:
    datasource:
     # 使用druid数据源
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
       view:
         prefix: /WEB-INF/
         suffix: .jsp
    freemarker:
       cache: true
       request-context-attribute: request
        

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
